283,100
284,"All N Elements code"
11,20230515004920
274,
18,0
275,
278,0
281,0
270,34
El Type
Year
Quarter
Month
Week
Week in Month
Day
Quarter Index
Month Index
Week Index
Weekday Index
Monthday Index
Yearday Index
DayNO
DateValue Excel
Day in Week
Day in Month
Day in Year
Julian Date
yyyy M00 dd
yyyy mmm dd
yyyymmdd
yyyy-mm-dd
First Day
Last Day
Caption zh-Hans
Caption zh-Hant
Day in Week zh-Hans
Day in Week zh-Hant
Calendar Day
Week Day
Weekend
Public Holiday - Input
Working Day - Weekend
