283,100
284,"APQ.Demo T Month - Description"
11,20200430185330
274,
18,0
275,
278,0
281,0
270,34
Group Total Year
Total Year
Quarter 1
Opening Balance
January
February
March
Quarter 2
April
May
June
Quarter 3
July
August
September
Quarter 4
October
November
December
Final Adjustment
Total Year Months
Total Year Entry
Total Year AVG
Q1 AVG
Q2 AVG
Q3 AVG
Q4 AVG
Relative Time
Last Month
Current Month
Next Month
Last Quarter
Current Quarter
Next Quarter
