283,100
284,"M UDC - Caption"
11,20201005064153
274,
18,0
275,
278,0
281,0
270,52
C1
C1 Desc
Sorting ID
P1
P2
P3
P4
P5
P6
P7
P8
P9
C1W
P1W
P2W
P3W
P4W
P5W
P6W
P7W
P8W
P9W
P1 Desc
P2 Desc
P3 Desc
P4 Desc
P5 Desc
P6 Desc
P7 Desc
P8 Desc
P9 Desc
Root Desc
All Levels
P1 Level
P2 Level
P3 Level
P4 Level
P5 Level
P6 Level
P7 Level
P8 Level
P9 Level
All Gens
P1 Gen
P2 Gen
P3 Gen
P4 Gen
P5 Gen
P6 Gen
P7 Gen
P8 Gen
P9 Gen
