283,100
284,"Data Source GL Plan"
11,20211106183021
274,
18,0
275,
278,0
281,0
270,7
Data Source GL Plan:Data Source GL Plan:All C Elements
Data Source GL Plan:Data Source GL Plan:All Elements
Data Source GL Plan:Data Source GL Plan:All N Elements
Data Source GL Plan:Data Source GL Plan:All N Elements code
Data Source GL Plan:Data Source GL Plan:Default Member
Data Source GL Plan:Data Source GL Plan:Top Elements
Data Source GL Plan:Data Source GL Plan:}Export.All
