283,100
284,"}APQ Cell Comment Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}APQ Cell Comment Measure:}APQ Cell Comment Measure:All Elements
}APQ Cell Comment Measure:}APQ Cell Comment Measure:All N Elements
}APQ Cell Comment Measure:}APQ Cell Comment Measure:All N Elements code
}APQ Cell Comment Measure:}APQ Cell Comment Measure:Default
}APQ Cell Comment Measure:}APQ Cell Comment Measure:Default Member
