283,100
284,"}APQ Cube Data Archive Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}APQ Cube Data Archive Measure:}APQ Cube Data Archive Measure:All Elements
}APQ Cube Data Archive Measure:}APQ Cube Data Archive Measure:All N Elements
}APQ Cube Data Archive Measure:}APQ Cube Data Archive Measure:All N Elements code
}APQ Cube Data Archive Measure:}APQ Cube Data Archive Measure:Default Member
