283,100
284,"}APQ Universal View  Format Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}APQ Universal View Format Measure:}APQ Universal View Format Measure:All Elements
}APQ Universal View Format Measure:}APQ Universal View Format Measure:All N Elements
}APQ Universal View Format Measure:}APQ Universal View Format Measure:All N Elements code
}APQ Universal View Format Measure:}APQ Universal View Format Measure:Default Member
