283,100
284,"}APQ Execution Item Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}APQ Execution Item Measure:}APQ Execution Item Measure:All Elements
}APQ Execution Item Measure:}APQ Execution Item Measure:All N Elements
}APQ Execution Item Measure:}APQ Execution Item Measure:All N Elements code
}APQ Execution Item Measure:}APQ Execution Item Measure:Default
}APQ Execution Item Measure:}APQ Execution Item Measure:Default Member
