283,100
284,"}APQ Chore Info Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}APQ Chore Info Measure:}APQ Chore Info Measure:All Elements
}APQ Chore Info Measure:}APQ Chore Info Measure:All N Elements
}APQ Chore Info Measure:}APQ Chore Info Measure:All N Elements code
}APQ Chore Info Measure:}APQ Chore Info Measure:Default
}APQ Chore Info Measure:}APQ Chore Info Measure:Default Member
