283,100
284,"}APQ Time Year-Month Lookup"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}APQ Time Year-Month Lookup:}APQ Time Year-Month Lookup:All Elements
}APQ Time Year-Month Lookup:}APQ Time Year-Month Lookup:All N Elements
}APQ Time Year-Month Lookup:}APQ Time Year-Month Lookup:All N Elements code
}APQ Time Year-Month Lookup:}APQ Time Year-Month Lookup:Default
}APQ Time Year-Month Lookup:}APQ Time Year-Month Lookup:Default Member
