283,100
284,"}APQ Universal View  Calculation Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}APQ Universal View Calculation Measure:}APQ Universal View Calculation Measure:All Elements
}APQ Universal View Calculation Measure:}APQ Universal View Calculation Measure:All N Elements
}APQ Universal View Calculation Measure:}APQ Universal View Calculation Measure:All N Elements code
}APQ Universal View Calculation Measure:}APQ Universal View Calculation Measure:Default Member
