283,100
284,"}APQ Picklist Dimension Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}APQ Picklist Dimension Measure:}APQ Picklist Dimension Measure:All Elements
}APQ Picklist Dimension Measure:}APQ Picklist Dimension Measure:All N Elements
}APQ Picklist Dimension Measure:}APQ Picklist Dimension Measure:All N Elements code
}APQ Picklist Dimension Measure:}APQ Picklist Dimension Measure:Default
}APQ Picklist Dimension Measure:}APQ Picklist Dimension Measure:Default Member
