283,100
284,"}APQ Time Month Conversion Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}APQ Time Month Conversion Measure:}APQ Time Month Conversion Measure:All Elements
}APQ Time Month Conversion Measure:}APQ Time Month Conversion Measure:All N Elements
}APQ Time Month Conversion Measure:}APQ Time Month Conversion Measure:All N Elements code
}APQ Time Month Conversion Measure:}APQ Time Month Conversion Measure:Default Member
