283,100
284,"}APQ Dimension Elements Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}APQ Dimension Elements Measure:}APQ Dimension Elements Measure:All Elements
}APQ Dimension Elements Measure:}APQ Dimension Elements Measure:All N Elements
}APQ Dimension Elements Measure:}APQ Dimension Elements Measure:All N Elements code
}APQ Dimension Elements Measure:}APQ Dimension Elements Measure:Default
}APQ Dimension Elements Measure:}APQ Dimension Elements Measure:Default Member
