283,100
284,"}APQ Dimension Subset Use Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}APQ Dimension Subset Use Measure:}APQ Dimension Subset Use Measure:All Elements
}APQ Dimension Subset Use Measure:}APQ Dimension Subset Use Measure:All N Elements
}APQ Dimension Subset Use Measure:}APQ Dimension Subset Use Measure:All N Elements code
}APQ Dimension Subset Use Measure:}APQ Dimension Subset Use Measure:Default Member
