283,100
284,"}APQ Picklist General Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}APQ Picklist General Measure:}APQ Picklist General Measure:All Elements
}APQ Picklist General Measure:}APQ Picklist General Measure:All N Elements
}APQ Picklist General Measure:}APQ Picklist General Measure:All N Elements code
}APQ Picklist General Measure:}APQ Picklist General Measure:Default
}APQ Picklist General Measure:}APQ Picklist General Measure:Default Member
