283,100
284,"}APQ Dimension Defaults Measure Type"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}APQ Dimension Defaults Measure Type:}APQ Dimension Defaults Measure Type:All Elements
}APQ Dimension Defaults Measure Type:}APQ Dimension Defaults Measure Type:All N Elements
}APQ Dimension Defaults Measure Type:}APQ Dimension Defaults Measure Type:All N Elements code
}APQ Dimension Defaults Measure Type:}APQ Dimension Defaults Measure Type:Default Member
