283,100
284,"}ElementAttributes_}APQ Time Year-Month"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_}APQ Time Year-Month:}ElementAttributes_}APQ Time Year-Month:Alias Attributes
}ElementAttributes_}APQ Time Year-Month:}ElementAttributes_}APQ Time Year-Month:All Elements
}ElementAttributes_}APQ Time Year-Month:}ElementAttributes_}APQ Time Year-Month:String & Alias Attributes
}ElementAttributes_}APQ Time Year-Month:}ElementAttributes_}APQ Time Year-Month:String Attributes
