283,100
284,"}ElementAttributes_}APQ Time Minute"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_}APQ Time Minute:}ElementAttributes_}APQ Time Minute:Alias Attributes
}ElementAttributes_}APQ Time Minute:}ElementAttributes_}APQ Time Minute:All Elements
}ElementAttributes_}APQ Time Minute:}ElementAttributes_}APQ Time Minute:String & Alias Attributes
}ElementAttributes_}APQ Time Minute:}ElementAttributes_}APQ Time Minute:String Attributes
