283,100
284,"}ElementAttributes_M FX Rate"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_M FX Rate:}ElementAttributes_M FX Rate:Alias Attributes
}ElementAttributes_M FX Rate:}ElementAttributes_M FX Rate:All Elements
}ElementAttributes_M FX Rate:}ElementAttributes_M FX Rate:String & Alias Attributes
}ElementAttributes_M FX Rate:}ElementAttributes_M FX Rate:String Attributes
