283,100
284,"}ElementAttributes_Day in Year"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}ElementAttributes_Day in Year:}ElementAttributes_Day in Year:Alias Attributes
}ElementAttributes_Day in Year:}ElementAttributes_Day in Year:All Elements
}ElementAttributes_Day in Year:}ElementAttributes_Day in Year:Numeric Attributes
}ElementAttributes_Day in Year:}ElementAttributes_Day in Year:String & Alias Attributes
}ElementAttributes_Day in Year:}ElementAttributes_Day in Year:String Attributes
