283,100
284,"}ElementAttributes_Month"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}ElementAttributes_Month:}ElementAttributes_Month:Alias Attributes
}ElementAttributes_Month:}ElementAttributes_Month:All Elements
}ElementAttributes_Month:}ElementAttributes_Month:Numeric Attributes
}ElementAttributes_Month:}ElementAttributes_Month:String & Alias Attributes
}ElementAttributes_Month:}ElementAttributes_Month:String Attributes
