283,100
284,"}ElementAttributes_Year Week"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_Year Week:}ElementAttributes_Year Week:Alias Attributes
}ElementAttributes_Year Week:}ElementAttributes_Year Week:All Elements
}ElementAttributes_Year Week:}ElementAttributes_Year Week:String & Alias Attributes
}ElementAttributes_Year Week:}ElementAttributes_Year Week:String Attributes
