283,100
284,"}ElementAttributes_Currency From"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_Currency From:}ElementAttributes_Currency From:Alias Attributes
}ElementAttributes_Currency From:}ElementAttributes_Currency From:All Elements
}ElementAttributes_Currency From:}ElementAttributes_Currency From:String & Alias Attributes
}ElementAttributes_Currency From:}ElementAttributes_Currency From:String Attributes
