283,100
284,"}ElementAttributes_Quarter"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}ElementAttributes_Quarter:}ElementAttributes_Quarter:Alias Attributes
}ElementAttributes_Quarter:}ElementAttributes_Quarter:All Elements
}ElementAttributes_Quarter:}ElementAttributes_Quarter:Numeric Attributes
}ElementAttributes_Quarter:}ElementAttributes_Quarter:String & Alias Attributes
}ElementAttributes_Quarter:}ElementAttributes_Quarter:String Attributes
