283,100
284,"}ElementAttributes_}APQ Dimension Attributes Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,3
}ElementAttributes_}APQ Dimension Attributes Measure:}ElementAttributes_}APQ Dimension Attributes Measure:All Elements
}ElementAttributes_}APQ Dimension Attributes Measure:}ElementAttributes_}APQ Dimension Attributes Measure:String & Alias Attributes
}ElementAttributes_}APQ Dimension Attributes Measure:}ElementAttributes_}APQ Dimension Attributes Measure:String Attributes
