283,100
284,"}ElementAttributes_Line Item"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_Line Item:}ElementAttributes_Line Item:Alias Attributes
}ElementAttributes_Line Item:}ElementAttributes_Line Item:All Elements
}ElementAttributes_Line Item:}ElementAttributes_Line Item:String & Alias Attributes
}ElementAttributes_Line Item:}ElementAttributes_Line Item:String Attributes
