283,100
284,"}ElementAttributes_FX Rate Type"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_FX Rate Type:}ElementAttributes_FX Rate Type:Alias Attributes
}ElementAttributes_FX Rate Type:}ElementAttributes_FX Rate Type:All Elements
}ElementAttributes_FX Rate Type:}ElementAttributes_FX Rate Type:String & Alias Attributes
}ElementAttributes_FX Rate Type:}ElementAttributes_FX Rate Type:String Attributes
