283,100
284,"}ElementAttributes_}APQ Universal View  Data Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,3
}ElementAttributes_}APQ Universal View Data Measure:}ElementAttributes_}APQ Universal View Data Measure:All Elements
}ElementAttributes_}APQ Universal View Data Measure:}ElementAttributes_}APQ Universal View Data Measure:String & Alias Attributes
}ElementAttributes_}APQ Universal View Data Measure:}ElementAttributes_}APQ Universal View Data Measure:String Attributes
