283,100
284,"}ElementAttributes_Year Month"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_Year Month:}ElementAttributes_Year Month:Alias Attributes
}ElementAttributes_Year Month:}ElementAttributes_Year Month:All Elements
}ElementAttributes_Year Month:}ElementAttributes_Year Month:String & Alias Attributes
}ElementAttributes_Year Month:}ElementAttributes_Year Month:String Attributes
