283,100
284,"}ElementAttributes_}APQ Time Year"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_}APQ Time Year:}ElementAttributes_}APQ Time Year:Alias Attributes
}ElementAttributes_}APQ Time Year:}ElementAttributes_}APQ Time Year:All Elements
}ElementAttributes_}APQ Time Year:}ElementAttributes_}APQ Time Year:String & Alias Attributes
}ElementAttributes_}APQ Time Year:}ElementAttributes_}APQ Time Year:String Attributes
