283,100
284,"}ElementAttributes_APQ.Demo T Year"
11,20200923043028
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_APQ.Demo T Year:}ElementAttributes_APQ.Demo T Year:Alias Attributes
}ElementAttributes_APQ.Demo T Year:}ElementAttributes_APQ.Demo T Year:All Elements
}ElementAttributes_APQ.Demo T Year:}ElementAttributes_APQ.Demo T Year:String & Alias Attributes
}ElementAttributes_APQ.Demo T Year:}ElementAttributes_APQ.Demo T Year:String Attributes
