283,100
284,"}ElementAttributes_Day in Week"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,5
}ElementAttributes_Day in Week:}ElementAttributes_Day in Week:Alias Attributes
}ElementAttributes_Day in Week:}ElementAttributes_Day in Week:All Elements
}ElementAttributes_Day in Week:}ElementAttributes_Day in Week:Numeric Attributes
}ElementAttributes_Day in Week:}ElementAttributes_Day in Week:String & Alias Attributes
}ElementAttributes_Day in Week:}ElementAttributes_Day in Week:String Attributes
