283,100
284,"}ElementAttributes_Currency To"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_Currency To:}ElementAttributes_Currency To:Alias Attributes
}ElementAttributes_Currency To:}ElementAttributes_Currency To:All Elements
}ElementAttributes_Currency To:}ElementAttributes_Currency To:String & Alias Attributes
}ElementAttributes_Currency To:}ElementAttributes_Currency To:String Attributes
