283,100
284,"}ElementAttributes_Day in Month"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,4
}ElementAttributes_Day in Month:}ElementAttributes_Day in Month:Alias Attributes
}ElementAttributes_Day in Month:}ElementAttributes_Day in Month:All Elements
}ElementAttributes_Day in Month:}ElementAttributes_Day in Month:Numeric Attributes
}ElementAttributes_Day in Month:}ElementAttributes_Day in Month:String & Alias Attributes
