283,100
284,"}ElementAttributes_}APQ Glossary Measure"
11,20230515004909
274,
18,0
275,
278,0
281,0
270,3
}ElementAttributes_}APQ Glossary Measure:}ElementAttributes_}APQ Glossary Measure:All Elements
}ElementAttributes_}APQ Glossary Measure:}ElementAttributes_}APQ Glossary Measure:String & Alias Attributes
}ElementAttributes_}APQ Glossary Measure:}ElementAttributes_}APQ Glossary Measure:String Attributes
