283,100
284,"All end user cubes"
11,20230515004943
274,
18,0
275,
278,0
281,0
270,21
EDU Employee Profile
EDU Training Plan
Employee Schedule
FX Rate
Public Holiday Reference
Sys Archive Parameter
Sys Archive Profile
Sys Dimension UDC
Sys Menu
Sys Menu Application Entry
Sys Menu Link
Sys Menu Parameter
Sys Module Object
Sys Parameter
Sys Time Attribute
Sys Versioning Cube
Sys Versioning Log
Sys Workbench
Sys Workbench Task Dependency
Sys Workflow Cooling Period
test
