283,100
284,"APQ.Demo T Fin Year-Period"
11,00000000000000
274,
18,0
275,
278,0
281,0
270,162
}Export.All
Relative Time -Next Year
Relative Time -Next Month
Relative Time -Last Year
Relative Time -Last Month
Relative Time -Current Year
Relative Time -Current Quarter
Relative Time -Current Month
Default Member
All N Elements
All N Elements code
All Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All Elements
All N Elements code
All N Elements
Default Member
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Relative Time -Current Year
Relative Time -Last Year
Relative Time -Next Year
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Relative Time -Current Year
Relative Time -Last Year
Relative Time -Next Year
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Relative Time -Current Month YTD
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Relative Time -Current Month
Relative Time -Last Month
Relative Time -Next Month
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Relative Time -Current Year
Relative Time -Last Year
Relative Time -Next Year
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Relative Time -Current Month YTD
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
