283,100
284,"APQ.Demo T Fin Year"
11,00000000000000
274,
18,0
275,
278,0
281,0
270,27
}Export.All
Default Member
All N Elements
All N Elements code
All Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All Elements
All N Elements code
All N Elements
Default Member
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
All C Elements
All Elements
All N Elements code
All N Elements
Default Member
Top Elements
