283,100
284,"String & Alias Attributes"
11,20230515004916
274,
18,0
275,
278,0
281,0
270,35
Description Short
Description
Period Name
ERP Date Format
Quarter
Last Month
Next Month
Idx0
Idx00
Month -12
Month -11
Month -10
Month -9
Month -8
Month -7
Month -6
Month -5
Month -4
Month -3
Month -2
Month -1
Month +1
Month +2
Month +3
Month +4
Month +5
Month +6
Month +7
Month +8
Month +9
Month +10
Month +11
Month +12
Short Name
Long Name
