389,100
390,"Default"
370,0
361,1
362,1
363,0
364,0
365,
366,
367,0
376,0
375,b:0.#########G|0|
374,1
7,}DimensionAttributes
270,0
274,
275,34
{[}DimensionAttributes].[Caption]}
281,0
282,
360,1
7,}Cultures
270,0
274,
275,179
{[}Cultures].[en],[}Cultures].[zh],[}Cultures].[zh-Hans],[}Cultures].[zh-Hant],[}Cultures].[zh-HK],[}Cultures].[zh-MO],[}Cultures].[zh-TW],[}Cultures].[zh-CN],[}Cultures].[zh-SG]}
281,0
282,
371,1
7,}Dimensions
270,0
274,
275,3992
{[}Dimensions].[}Dimensions].[Currency From],[}Dimensions].[}Dimensions].[Currency To],[}Dimensions].[}Dimensions].[Data Source GL],[}Dimensions].[}Dimensions].[Data Source GL Plan],[}Dimensions].[}Dimensions].[Data Source Sales],[}Dimensions].[}Dimensions].[Date],[}Dimensions].[}Dimensions].[Day in Month],[}Dimensions].[}Dimensions].[Day in Week],[}Dimensions].[}Dimensions].[Day in Year],[}Dimensions].[}Dimensions].[Demo Account GL],[}Dimensions].[}Dimensions].[Demo Account GL Plan],[}Dimensions].[}Dimensions].[Demo Account Sales],[}Dimensions].[}Dimensions].[Demo Customer],[}Dimensions].[}Dimensions].[Demo Entity],[}Dimensions].[}Dimensions].[Demo Product],[}Dimensions].[}Dimensions].[Demo Profit Center],[}Dimensions].[}Dimensions].[Exchange Rate Type],[}Dimensions].[}Dimensions].[Line Item],[}Dimensions].[}Dimensions].[Manpower Title],[}Dimensions].[}Dimensions].[M Currency],[}Dimensions].[}Dimensions].[M Exchange Rate],[}Dimensions].[}Dimensions].[M GL Plan],[}Dimensions].[}Dimensions].[M GL Reporting],[}Dimensions].[}Dimensions].[M Manpower Reporting],[}Dimensions].[}Dimensions].[Month],[}Dimensions].[}Dimensions].[M Reference],[}Dimensions].[}Dimensions].[M Sales Reporting],[}Dimensions].[}Dimensions].[M Sys Archive Parameter],[}Dimensions].[}Dimensions].[M Sys Archive Profile],[}Dimensions].[}Dimensions].[M Sys Menu],[}Dimensions].[}Dimensions].[M Sys Menu Application Entry],[}Dimensions].[}Dimensions].[M Sys Menu Link],[}Dimensions].[}Dimensions].[M Sys Menu Parameter],[}Dimensions].[}Dimensions].[M Sys Module Object],[}Dimensions].[}Dimensions].[M Sys Parameter],[}Dimensions].[}Dimensions].[M Sys Time Attribute],[}Dimensions].[}Dimensions].[M Sys Versioning Cube],[}Dimensions].[}Dimensions].[M Sys Versioning Log],[}Dimensions].[}Dimensions].[M Sys Workbench],[}Dimensions].[}Dimensions].[M Sys Workbench Task Dependency],[}Dimensions].[}Dimensions].[M Sys Workflow Cooling Period],[}Dimensions].[}Dimensions].[M UDC],[}Dimensions].[}Dimensions].[M Unit],[}Dimensions].[}Dimensions].[M Workflow],[}Dimensions].[}Dimensions].[Planning Year],[}Dimensions].[}Dimensions].[Profit Center],[}Dimensions].[}Dimensions].[Quarter],[}Dimensions].[}Dimensions].[Scenario],[}Dimensions].[}Dimensions].[Sys Archive ID],[}Dimensions].[}Dimensions].[Sys Archive Parameter],[}Dimensions].[}Dimensions].[Sys Lookup Date],[}Dimensions].[}Dimensions].[Sys Lookup Year Month],[}Dimensions].[}Dimensions].[Sys Lookup Year Quarter],[}Dimensions].[}Dimensions].[Sys Lookup Year Week],[}Dimensions].[}Dimensions].[Sys Menu Application Entry],[}Dimensions].[}Dimensions].[Sys Menu Group],[}Dimensions].[}Dimensions].[Sys Menu Link],[}Dimensions].[}Dimensions].[Sys Menu Link Measure],[}Dimensions].[}Dimensions].[Sys Menu Measure],[}Dimensions].[}Dimensions].[Sys Menu Page],[}Dimensions].[}Dimensions].[Sys Menu Page Column],[}Dimensions].[}Dimensions].[Sys Menu Page Pattern],[}Dimensions].[}Dimensions].[Sys Menu Page Row],[}Dimensions].[}Dimensions].[Sys Menu Parameter],[}Dimensions].[}Dimensions].[Sys Menu Profile],[}Dimensions].[}Dimensions].[Sys Module],[}Dimensions].[}Dimensions].[Sys Module Object Type],[}Dimensions].[}Dimensions].[Sys Parameter],[}Dimensions].[}Dimensions].[Sys Security Access Right],[}Dimensions].[}Dimensions].[Sys Security Data Parameter],[}Dimensions].[}Dimensions].[Sys Security Group],[}Dimensions].[}Dimensions].[Sys Security Object Type],[}Dimensions].[}Dimensions].[Sys Versioning Module],[}Dimensions].[}Dimensions].[Sys Workbench Group],[}Dimensions].[}Dimensions].[Sys Workbench Priority],[}Dimensions].[}Dimensions].[Sys Workbench Step],[}Dimensions].[}Dimensions].[Sys Workflow],[}Dimensions].[}Dimensions].[Time Deviation],[}Dimensions].[}Dimensions].[UDC],[}Dimensions].[}Dimensions].[UDC Dimension],[}Dimensions].[}Dimensions].[Version],[}Dimensions].[}Dimensions].[Week],[}Dimensions].[}Dimensions].[Year],[}Dimensions].[}Dimensions].[Year Fiscal],[}Dimensions].[}Dimensions].[Year Month],[}Dimensions].[}Dimensions].[Year Week]}
281,0
282,
373,1
1,Caption
372,0
372,00
384,0
385,0
377,4
1136
411
1929
942
378,0
382,255
379,3
0
0
0
11,20200405013715
381,0
32,6
null\n
