283,100
284,"All N Elements code"
11,20230515004922
274,
18,0
275,
278,0
281,0
270,22
Automatic Alias
Alias Override
Default_Alias
Automatic Default
Default Override
Default_Member
Automatic NA
NA Override
NA_Member
Automatic Total
Total Override
Total_Member
Caption Autofill
Caption Name
Caption Type
Caption Source
Std All Elements
Std All N Elements
Std All N Elements Principal
Std All C Elements
Std Top Elements
Std Default Member Subset
