283,100
284,"Dimensions without cubes (excl. control obj.)"
11,20230515004943
274,
18,0
275,
278,0
281,0
270,23
Data Source GL
Data Source Sales
Day in Month
Day in Week
Demo Inter Company
M Currency
M Employee Working Day
M GL Reporting
M Reference
M Sales Reporting
M Unit
M Workflow
Planning Year
Quarter
Sys Lookup Date
Sys Lookup Year
Sys Lookup Year Fiscal
Sys Lookup Year Month
Sys Lookup Year Quarter
Sys Lookup Year Week
Week
Year Fiscal
Year Week
